### ISSUE TITLE
Composer not completing successfully

### ISSUE THREAD

**Issue by pkarjala** [dreamfactorysoftware/platform-packages#1]
When following the instructions at http://wiki.dreamfactory.com/wiki/Packages/Deb and getting to the step to run:

sudo dpkg -i dreamfactory-dsp_1.2.3-0_all.deb

The installer runs, but has the following error during install:

ubuntu@test-df:~$ sudo dpkg -i dreamfactory-dsp_1.2.3-0_all.deb
Selecting previously unselected package dreamfactory-dsp.
(Reading database ... 76090 files and directories currently installed.)
Unpacking dreamfactory-dsp (from dreamfactory-dsp_1.2.3-0_all.deb) ...
Setting up dreamfactory-dsp (1.2.3-0) ...
DreamFactory Services Platform(tm) Linux Installer [Mode: Local v1.2.9]
- Clean install. Dependencies removed.
- No composer found, installing: /opt/dreamfactory/platform/var/www/launchpad/composer.phar
  #!/usr/bin/env php
- Install user is "root"
- Checking file system
- Working directory: /opt/dreamfactory/platform/var/www/launchpad
- Installing dependencies
- ERROR: Composer did not complete successfully (0). Some features may not operate properly.
- Created /opt/dreamfactory/platform/var/www/launchpad/log/
- Created /opt/dreamfactory/platform/var/www/launchpad/storage/
- Created /opt/dreamfactory/platform/var/www/launchpad/web/assets

Complete. Enjoy the rest of your day!

The issue lies in the line

ERROR: Composer did not complete successfully (0). Some features may not operate properly.

After the install and running a2dissite default, attempting to access the site results in a blank page, and the following in logs:

[Fri Feb 21 10:06:32 2014] [error] [client 172.17.0.199] PHP Warning:  require_once(/opt/dreamfactory/platform/var/www/launchpad/web/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/dreamfactory/platform/var/www/launchpad/web/index.php on line 25
[Fri Feb 21 10:06:32 2014] [error] [client 172.17.0.199] PHP Fatal error:  require_once(): Failed opening required '/opt/dreamfactory/platform/var/www/launchpad/web/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /opt/dreamfactory/platform/var/www/launchpad/web/index.php on line 25

Checking line 25 in index.php shows:

$_autoloader = require_once( __DIR__ . '/../vendor/autoload.php' );

The problem becomes apparent due to the directory launchpad/vendor/ not existing on the install.  So for some reason when running the dpkg, this directory is not being generated.

Checking the installer script at https://github.com/dreamfactorysoftware/dsp-core/blob/master/scripts/installer.sh, the original error is thrown on this line:

if [ ${NO_COMPOSER} -eq 0 ] ; then
    if [ ! -d "${VENDOR_DIR}" ] ; then
        _info "Installing dependencies"
        ${PHP} ${COMPOSER_DIR}/${COMPOSER} ${QUIET} ${VERBOSE} --no-interaction install ; _code=$?
    else
        _info "Updating dependencies"
        ${PHP} ${COMPOSER_DIR}/${COMPOSER} ${QUIET} ${VERBOSE} --no-interaction update ; _code=$?
    fi

```
[ ${_code} -ne 0 ] && _error "Composer did not complete successfully (${_code}). Some features may not operate properly."
```

fi

I am going to try this setup on a Vagrant box to see if the error can be duplicated.

**Comment by df-jablan** [comment]
Hey pat-trick, thanks for reporting this.

The packages in the repository are an older, unsupported release. We are no longer making new RPM/DEB packages. Instead we are now using BitNami to distribute our stack. It's an all-in-one install and works very well.

Please grab a copy from there (link below) and let us know if we can help with anything else!

BitNami DreamFactory Stacks: http://bitnami.com/stack/dreamfactory

**Comment by pkarjala** [comment]
AOK; might be good to update the wiki with this information!

**Comment by df-jablan** [comment]
Indeed. Next sprint. ;)
